export interface SnapchatOrganization {
  id: string,
  updated_at: string,
  created_at: string,
  name: string,
  country: string,
  postal_code: string,
  locality: string,
  contact_name: string,
  contact_email: string,
  contact_phone: string,
  address_line_1: string,
  administrative_district_level_1: string,
  accepted_term_version: string,
  contact_phone_optin: boolean,
  configuration_settings: {
    notifications_enabled: boolean,
  },
  type: string,
  state: string,
  roles: string[],
  my_display_name: string,
  my_invited_email: string,
  my_member_id: string,
  createdByCaller: boolean,
}